wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1673405211
    t:
      1:
      - 1
      - 5
      - 9
      4: 3.8.15
      5: 0.12.1
      8:
      - 5
